In [ ]:
!pip install numpy

In [ ]:
import numpy as np

Kami mempersingkat nama yang diimpor menjadi np agar kode lebih mudah dibaca menggunakan NumPy. Ini adalah
konvensi yang diadopsi secara luas yang membuat kode Anda lebih mudah dibaca oleh semua orang yang mengerjakannya.
Kami menyarankan untuk selalu menggunakan import numpy sebagai np

Membaca kode contoh

Jika Anda belum terbiasa membaca tutorial yang berisi banyak kode, Anda mungkin tidak tahu cara menafsirkan blok
kode yang terlihat seperti ini:

In [ ]:
a =np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

Jika Anda belum familiar dengan gaya ini, sangat mudah untuk memahaminya. Jika Anda melihat >>>, berarti Anda sedang
melihat input, atau kode yang akan Anda masukkan. Segala sesuatu yang tidak memiliki >>> di depannya adalah
keluaran, atau hasil dari menjalankan kode Anda. Ini adalah gaya yang Anda lihat saat menjalankan python di baris perintah,
tetapi jika Anda menggunakan IPython, Anda mungkin melihat gaya yang berbeda. Perhatikan bahwa ini bukan bagian
dari kode dan akan menyebabkan kesalahan jika diketik atau ditempel ke dalam shell Python. Itu dapat diketik atau ditempel
dengan aman ke dalam shell IPython; >>> diabaikan.

Array adalah struktur data pusat perpustakaan NumPy. Array adalah kisi-kisi nilai dan berisi informasi tentang data
mentah, cara menemukan lokasi elemen, dan cara menafsirkan elemen. Ini memiliki kisi elemen yang dapat diindeks
dengan berbagai cara. Semua elemen memiliki tipe yang sama, disebut sebagai array dtype.

Sebuah array dapat diindeks dengan serangkaian bilangan bulat non-negatif, dengan boolean, dengan array lain, atau
dengan bilangan bulat. Peringkat array adalah jumlah dimensi. Bentuk array adalah kumpulan bilangan bulat yang
memberikan ukuran array di setiap dimensinya.
Salah satu cara kita menginisialisasi array NumPy adalah dari daftar Python, menggunakan daftar bersarang untuk
data dua dimensi atau lebih tinggi.
Misalnya:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

Kita dapat mengakses elemen-elemen dalam array menggunakan tanda kurung siku. Saat Anda mengakses elemen, ingatlah bahwa pengindeksan di NumPy dimulai dari 0. Artinya, jika Anda ingin mengakses elemen pertama dalam array, Anda akan mengakses elemen “0”.

Cara membuat array dasar

Bagian ini mencakup np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

Untuk membuat array NumPy, Anda dapat menggunakan fungsi np.array().

Yang perlu Anda lakukan untuk membuat array sederhana adalah meneruskan daftar ke dalamnya. Jika Anda memilihnya, Anda
juga dapat menentukan tipe data dalam daftar Anda. Anda dapat menemukan informasi selengkapnya tentang tipe data di sini.

In [ ]:
import numpy as np
a = np.array([1, 2, 3,])
print(a)

[1 2 3]


Sadarilah bahwa visualisasi ini dimaksudkan untuk menyederhanakan ide dan memberi Anda pemahaman dasar

tentang konsep dan mekanika NumPy. Operasi array dan array jauh lebih rumit daripada yang digambarkan di sini!

Anda dapat membuat array dengan berbagai elemen:

Anda dapat memvisualisasikan array Anda dengan cara ini: dengan 0:

In [ ]:
np.zeros(2)

array([0., 0.])

Atau array yang diisi dengan 1:

In [ ]:
np.ones(2)

array([1., 1.])

Atau bahkan array kosong! Fungsi kosong membuat array yang konten awalnya acak dan bergantung pada keadaan
memori. Alasan menggunakan kosong di atas nol (atau yang serupa) adalah kecepatan - pastikan untuk mengisi setiap
elemen setelahnya!

In [ ]:
np.empty(2)

array([1., 1.])

Anda dapat membuat array dengan berbagai elemen:

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

Dan bahkan array yang berisi rentang interval yang berjarak sama. Untuk melakukan ini, Anda akan menentukan
angka pertama, angka terakhir, dan ukuran langkah.

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

Anda juga dapat menggunakan np.linspace() untuk membuat array dengan nilai yang diberi jarak linier dalam interval
tertentu:

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Menentukan tipe data Anda

Meskipun tipe data defaultnya adalah floating point (np.float64), Anda dapat secara eksplisit menentukan tipe data
mana yang Anda inginkan menggunakan kata kunci dtype .

In [ ]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1])

Mengurutkan elemen itu mudah dengan np.sort(). Anda dapat menentukan sumbu, jenis, dan urutan
saat memanggil fungsi.

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Anda dapat dengan cepat mengurutkan angka dalam urutan menaik dengan:

Jika Anda memulai dengan array ini:

In [ ]:
a = np.array([1, 2, 3,4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Anda dapat menggabungkannya dengan np.concatenate().

In [ ]:
x =np.array([[1, 2], [3, 4]])
y =np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Atau, jika Anda memulai dengan array berikut:

Untuk menghapus elemen dari array, cukup gunakan pengindeksan untuk memilih elemen yang ingin
Anda pertahankan.

In [ ]:
array_example= np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],

                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]],

                         [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])
array_example.ndim

3

Bagaimana cara mengetahui bentuk dan ukuran array?
ndarray.ndim akan memberi tahu Anda jumlah sumbu, atau dimensi, dari array.
[[0 ,1 ,2, 3],
Untuk menemukan jumlah total elemen dalam array, jalankan:
Dan untuk menemukan bentuk array Anda, jalankan:
...
ndarray.shape akan menampilkan tupel bilangan bulat yang menunjukkan jumlah elemen
yang disimpan di setiap dimensi array. Jika, misalnya, Anda memiliki array ini:

In [ ]:
array_example.size

24

Untuk menemukan jumlah total elemen dalam array, jalankan:

In [ ]:
array_example.shape

(3, 2, 4)

Menggunakan arr.reshape() akan memberikan bentuk baru pada array tanpa mengubah
datanya. Ingatlah bahwa ketika Anda menggunakan metode reshape, array yang ingin Anda
hasilkan harus memiliki jumlah elemen yang sama dengan array aslinya. Jika Anda memulai
dengan array dengan 12 elemen, Anda harus memastikan bahwa array baru Anda juga memiliki total 12 elemen maka jalankan ini:

In [ ]:
a =np.arange(6)
print(a)

[0 1 2 3 4 5]


Anda dapat menggunakan reshape() untuk membentuk ulang array Anda. Misalnya, Anda bisa membentuk ulang larik
ini menjadi larik dengan tiga baris dan dua kolom:

In [ ]:
b =a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional:

In [ ]:
np.reshape(a, newshape = (1, 6), order = 'c')

array([[1, 2, 3, 4, 5, 6]])

a adalah array yang akan dibentuk ulang.
newshape adalah bentuk baru yang Anda inginkan. Anda dapat menentukan bilangan bulat atau tupel bilangan bulat.
Jika Anda menentukan bilangan bulat, hasilnya akan berupa array dengan panjang tersebut. Bentuknya harus sesuai
dengan bentuk aslinya.

Menggunakan np.newaxis akan menambah dimensi array Anda sebanyak satu dimensi bila digunakan sekali.
Artinya array 1D akan menjadi array 2D , array 2D akan menjadi array 3D , dan seterusnya.

urutan: C berarti membaca/menulis elemen menggunakan urutan indeks mirip C, F berarti membaca/menulis elemen
menggunakan urutan indeks mirip Fortran, A berarti membaca/menulis elemen dalam urutan indeks mirip Fortran
jika a adalah Fortran bersebelahan dalam memori, urutan seperti C sebaliknya. (Ini adalah parameter opsional
dan tidak perlu ditentukan.)

Misalnya, jika Anda memulai dengan array ini:

In [ ]:
a = np.array([1,2,3,4,5,6])

Anda dapat menggunakan np.newaxis untuk menambahkan sumbu baru:

Anda dapat secara eksplisit mengonversi array 1D dengan vektor baris atau vektor kolom menggunakan
np.newaxis. Misalnya, Anda dapat mengonversi array 1D menjadi vektor baris dengan menyisipkan sumbu
di sepanjang dimensi pertama:

In [ ]:
a2 = a[np.sumbu baru,:]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-81-1f1ed7f772f4>, line 1)

Anda dapat secara eksplisit mengonversi array 1D dengan vektor baris atau vektor kolom menggunakan

np.newaxis. Misalnya, Anda dapat mengonversi array 1D menjadi vektor baris dengan menyisipkan sumbu

di sepanjang dimensi pertama:

In [ ]:
vektor_baris = a[np.sumbu baru,:]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-82-c12116f1c1c8>, line 1)

Atau, untuk vektor kolom, Anda bisa menyisipkan sumbu sepanjang dimensi kedua:

In [ ]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [ ]:
col_vector = a[: ,np.newaxis]
col_vector.shape

(6, 1)

Anda juga dapat memperluas array dengan menyisipkan sumbu baru pada posisi tertentu
dengan np.expand_dims.

Misalnya, jika Anda memulai dengan array ini:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

Anda dapat menggunakan np.expand_dims untuk menambahkan sumbu pada posisi indeks 1 dengan:

In [ ]:
b = np.expand_dims(a, sumbu=1)
b.

TypeError: expand_dims() got an unexpected keyword argument 'sumbu'

Anda dapat menambahkan sumbu pada posisi indeks 0 dengan:

In [ ]:
c = np.expand_dims(a, axis=0)
c. bentuk

AttributeError: 'numpy.ndarray' object has no attribute 'bentuk'

In [ ]:
data = np.array([1, 2, 3])
data[1]
data [0:2]
data[1:]
data[-2:]

NameError: name 'np' is not defined

Anda mungkin ingin mengambil bagian dari array Anda atau elemen array tertentu untuk digunakan dalam analisis lebih lanjut atau operasi tambahan. Untuk melakukan itu, Anda perlu membuat subset, mengiris, dan/atau mengindeks file Anda Anda dapat memilih elemen yang habis dibagi 2:

Misalnya, jika Anda memulai dengan array ini:

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[a < 5])

NameError: name 'np' is not defined

Anda dapat dengan mudah mencetak semua nilai dalam array yang kurang dari 5.

In [ ]:
five_up = (a >= 5)
print(a[five_up])

NameError: name 'a' is not defined

Anda juga dapat memilih, misalnya, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi
tersebut untuk mengindeks array.

In [ ]:
dibagi_oleh_2 = a[a%2==0]
print(dibagi_oleh_2)

[2 4 6]


Anda dapat memilih elemen yang habis dibagi 2:

In [ ]:
c = a[(a > 2) & (a < 11)]
cetak(c)

NameError: name 'cetak' is not defined

Atau Anda dapat memilih elemen yang memenuhi dua kondisi menggunakan & dan | operator:

In [ ]:
five_up = (a > 5) | (a == 5)
print(five_up)

[False False False False  True  True]


Anda juga dapat menggunakan np.nonzero() untuk memilih elemen atau indeks dari array.

Dimulai dengan array ini:

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Anda dapat menggunakan np.nonzero() untuk mencetak indeks elemen yang, misalnya, kurang dari 5:

In [ ]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


Jika Anda ingin membuat daftar koordinat tempat elemen berada, Anda dapat meng-zip array,
mengulangi daftar koordinat, dan mencetaknya. Misalnya:

In [ ]:
daftar_koordinat_= daftar(zip(b[0], b[1]))
untuk koordinat di list_of_koordinat:
      print(coord)

SyntaxError: invalid syntax (<ipython-input-93-ad0a3dce3f10>, line 2)

Anda juga dapat menggunakan np.nonzero() untuk mencetak elemen dalam array yang kurang dari 5 dengan:

In [ ]:
print(a[b])

[1 2 3 4]


Jika elemen yang Anda cari tidak ada dalam array, maka array indeks yang dikembalikan akan
kosong. Misalnya:

In [ ]:
not_there = np.nonzero(a == 42)
>>> print(not_there)

(array([], dtype=int64), array([], dtype=int64))


Bagian ini mencakup pemotongan dan pengindeksan, np.vstack(), np.hstack(), np.hsplit(), .view(),
copy()

Anda dapat dengan mudah membuat array baru dari bagian array yang sudah ada.
Katakanlah Anda memiliki array ini:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Anda dapat membuat array baru dari suatu bagian array kapan saja dengan menentukan di mana
Anda ingin mengiris array Anda.

In [ ]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

Anda juga dapat menumpuk dua array yang ada, baik secara vertikal maupun horizontal. Katakanlah Anda memiliki
dua array, a1 dan a2:
Pelajari lebih lanjut tentang pengindeksan dan pemotongan di sini dan di sini.
Jika Anda ingin membuat daftar koordinat tempat elemen berada, Anda dapat meng-zip array,
mengulangi daftar koordinat, dan mencetaknya. Misalnya:
D

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Anda dapat menumpuknya secara vertikal dengan vstack:

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Atau susun secara horizontal dengan hstack:

Anda dapat membagi array menjadi beberapa array yang lebih kecil menggunakan hsplit. Anda
dapat menentukan jumlah array berbentuk sama yang akan dikembalikan atau kolom setelah pembagian
terjadi.

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Jika Anda ingin membagi array ini menjadi tiga array yang bentuknya sama, jalankan:

In [ ]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Jika Anda ingin membagi array setelah kolom ketiga dan keempat, jalankan:

In [ ]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

Tampilan adalah konsep NumPy yang penting! Fungsi NumPy, serta operasi seperti pengindeksan dan
pemotongan, akan mengembalikan tampilan bila memungkinkan. Ini menghemat memori dan lebih
cepat (tidak perlu membuat salinan data). Namun penting untuk menyadari hal ini - mengubah data
dalam tampilan juga mengubah array asli!

Katakanlah Anda membuat array ini:

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Sekarang kita membuat array b1 dengan mengiris a dan memodifikasi elemen pertama b1. Ini juga akan mengubah
elemen terkait di a !

In [ ]:
b1 = a[0,:]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Menggunakan metode copy akan membuat salinan lengkap dari array dan datanya ( salinan dalam). Untuk
menggunakan ini pada array Anda, Anda bisa menjalankan:

In [ ]:
b2 = a.copy()

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)
data + satuan

NameError: name 'satuan' is not defined

Pengoperasian dasar sederhana dengan NumPy. Jika Anda ingin mencari jumlah elemen dalam array, Anda akan
menggunakan sum(). Ini berfungsi untuk array 1D, array 2D, dan array dalam dimensi yang lebih tinggi

In [ ]:
data - array satuan
data * data
data / data

SyntaxError: invalid syntax (<ipython-input-113-36473832067f>, line 1)

Untuk menambahkan baris atau kolom dalam array 2D, Anda harus menentukan sumbunya.

Jika Anda memulai dengan array ini:

In [ ]:
a = np.array([1, 2, 3, 4])
a.sum()

10

Anda dapat menjumlahkan sumbu baris dengan:

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

Anda dapat menjumlahkan sumbu kolom dengan:

In [ ]:
b.sum(axis=1)

array([2, 4])

Penyiaran

Ada kalanya Anda mungkin ingin melakukan operasi antara array dan satu bilangan (disebut juga operasi antara vektor
dan skalar) atau antara array dengan dua ukuran berbeda. Misalnya, array Anda (kita akan sebut saja "data")
mungkin berisi informasi tentang jarak dalam mil tetapi Anda ingin mengonversi informasi tersebut menjadi kilometer.
Anda dapat melakukan operasi ini dengan:

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

NumPy memahami bahwa perkalian harus terjadi pada setiap sel. Konsep itu disebut penyiaran. Penyiaran adalah
mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda. Dimensi array Anda
harus kompatibel, misalnya, ketika dimensi kedua array sama atau ketika salah satunya adalah 1. Jika dimensinya sama
tidak kompatibel, Anda akan mendapatkan ValueError.

In [ ]:
data.max()
data.min()
data.sum()

3.0

Mari kita mulai dengan array ini, yang disebut “a”

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
[0.54627315, 0.05093587, 0.40067661, 0.55645993],
[0.12697628, 0.82485143, 0.26590556, 0.56917101]])

Sangat umum untuk ingin menggabungkan sepanjang baris atau kolom. Secara default, setiap fungsi
agregasi NumPy akan mengembalikan agregat seluruh array. Untuk menemukan jumlah atau jumlah
minimum elemen dalam array Anda, jalankan:

In [ ]:
a.sum()

4.8595784

Atau:

In [ ]:
a.min()

0.05093587

Anda dapat menentukan pada sumbu mana Anda ingin fungsi agregasi dihitung. Misalnya, Anda
dapat menemukan nilai minimum dalam setiap kolom dengan menentukan sumbu=0.

In [ ]:
a.min(sumbu=0)

TypeError: _amin() got an unexpected keyword argument 'sumbu'



Keempat nilai yang tercantum di atas sesuai dengan jumlah kolom dalam array Anda. Dengan array empat
kolom, Anda akan mendapatkan empat nilai sebagai hasilnya.

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

Operasi pengindeksan dan pemotongan berguna saat Anda memanipulasi matriks:

In [ ]:
data[0, 1]
data [1:3]
data [0:2, 0]

array([1, 3])

Anda dapat mengagregasi matriks dengan cara yang sama seperti Anda mengagregasi vektor:

In [ ]:
data.max()
data.min()
data.sum()

21

Anda dapat menggabungkan semua nilai dalam matriks dan Anda dapat menggabungkannya di seluruh kolom atau
baris menggunakan parameter sumbu . Untuk mengilustrasikan hal ini, mari kita lihat kumpulan data yang sedikit dimodifikasi:

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

Setelah Anda membuat matriks, Anda dapat menjumlahkan dan mengalikannya menggunakan operator
aritmatika jika Anda memiliki dua matriks yangberukuran sama.

Anda dapat melakukan operasi aritmatika ini pada matriks dengan ukuran berbeda, tetapi hanya jika satu matriks
hanya memiliki satu kolom atau satu baris. Dalam hal ini, NumPy akan menggunakan aturan siarannya untuk
operasi tersebut.

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + satu

NameError: name 'satuan' is not defined

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + larik satu_baris

Perlu diketahui bahwa saat NumPy mencetak array berdimensi N, sumbu terakhir dilingkarkan pada sumbu tercepat
sedangkan sumbu pertama adalah sumbu paling lambat. Contohnya:

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Sering kali kita ingin NumPy menginisialisasi nilai array. NumPy menawarkan fungsi seperti satu() dan nol(), dan kelas
random.Generator untuk acak.

pembuatan nomor untuk itu. Yang perlu Anda lakukan hanyalah memasukkan jumlah elemen yang ingin Anda hasilkan:

In [ ]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()
rng.random(3)

array([0.46629348, 0.08475388, 0.80835093])

Anda juga dapat menggunakan one(), zeros(), dan random() untuk membuat array 2D jika Anda memberinya tupel
yang menjelaskan dimensi matriks:

In [ ]:
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))

array([[0.15887415, 0.08001325],
       [0.54897427, 0.25093132],
       [0.21344632, 0.57617195]])

Dengan Generator.integers, Anda dapat menghasilkan bilangan bulat acak dari rendah (ingat bahwa ini inklusif
dengan NumPy) hingga tinggi (eksklusif). Anda dapat mengatur endpoint=True untuk mencapai nilai tertinggi.

Anda dapat menghasilkan array bilangan bulat acak berukuran 2 x 4 antara 0 dan 4 dengan:

In [ ]:
rng.integers(5, size=(2, 4))

array([[3, 2, 0, 4],
       [1, 2, 2, 3]])

Misalnya, jika Anda memulai dengan array ini:

In [ ]:
a = np.array([11, 11, 12, 13, 14, 14, 15, 16, 17, 12, 13, 11, 14, 18,
19, 20])

Anda dapat menggunakan np.unique untuk mencetak nilai unik dalam array Anda:

In [ ]:
nilai_unik = np.unique(a)
print(nilai_unik)

[11 12 13 14 15 16 17 18 19 20]


Ini juga berfungsi dengan array 2D! Jika Anda memulai dengan array ini:

In [ ]:
nilai_unik, daftar_indeks = np.unique(a, return_indeks = True)
print(indices_list)

TypeError: unique() got an unexpected keyword argument 'return_indeks'

In [ ]:
nilai_unik, jumlah_kejadian = np.unik(a, jumlah_kembali = True)
print(jumlah_kejadian)

AttributeError: module 'numpy' has no attribute 'unik'

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1,
2, 3, 4]])

Anda dapat menemukan nilai unik dengan:

In [ ]:
nilai_unik = np.unique(a_2d)
print(nilai_unik)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Jika Anda ingin mendapatkan baris atau kolom unik, pastikan untuk meneruskan argumen sumbu . Untuk
menemukan baris unik, tentukan sumbu=0 dan untuk kolom, tentukan sumbu=1.

In [ ]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Untuk mendapatkan baris unik, posisi indeks, dan jumlah kemunculan, Anda dapat menggunakan:

In [ ]:
unique_rows, indices, occurrence_count = np.unique(

a_2d, axis=0, return_counts = True, return_index = True)
print(unique_rows)

print(indices)

 print(jumlah_kejadian)

IndentationError: unexpected indent (<ipython-input-148-d8d2781c1f4e>, line 8)

Anda mungkin juga perlu mengganti dimensi matriks. Hal ini dapat terjadi ketika, misalnya, Anda
memiliki model yang mengharapkan bentuk masukan tertentu yang berbeda dari kumpulan data
Anda. Di sinilah metode pembentukan ulang dapat berguna. Anda hanya perlu memasukkan
dimensi baru yang Anda inginkan. matriks.

In [ ]:
data.reshape(2, 3)

data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Anda juga dapat menggunakan .transpose() untuk membalikkan atau mengubah sumbu array sesuai dengan
nilai yang Anda tentukan.

Jika Anda memulai dengan array ini:

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

Anda dapat mengubah urutan array Anda dengan arr.transpose().

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

Anda juga dapat menggunakan arr.T:

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

Untuk mempelajari selengkapnya tentang transpos dan pembentukan ulang array, lihat transpos dan membentuk kembali.

Cara membalikkan array

Membalikkan array 1D
Jika Anda memulai dengan array 1D seperti ini:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Anda dapat membalikkannya dengan:

In [ ]:
reversed_arr = np.flip(arr)

Membalikkan array 2D
Array 2D bekerja dengan cara yang hampir sama.

In [ ]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


Anda dapat dengan mudah membalikkan baris saja dengan:

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Atau balikkan hanya kolom dengan:

In [ ]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Membentuk kembali dan meratakan array multidimensi
Ada dua cara populer untuk meratakan array: .flatten() dan .ravel(). Perbedaan utama antara
keduanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya adalah
referensi ke array induk (yaitu, “tampilan”). Ini berarti bahwa setiap perubahan pada array baru akan
mempengaruhi induknya. susunan juga. Karena ravel tidak membuat salinan, memorinya efisien.

In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Anda dapat menggunakan flatten untuk meratakan array Anda menjadi array 1D.

In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [ ]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Saat Anda menggunakan flatten, perubahan pada array baru Anda tidak akan mengubah array induk.
 Misalnya

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


Namun saat Anda menggunakan ravel, perubahan yang Anda buat pada array baru akan memengaruhi array induk. Misalnya

In [ ]:
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


Baca selengkapnya tentang perataan di ndarray.flatten dan berceloteh demi berceloteh.

Cara mengakses docstring untuk informasi lebih lanjut

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

Kemudian Anda dapat memperoleh banyak informasi berguna (detail pertama tentang a itu sendiri, diikuti oleh
docstring dari ndarray yang mana a merupakan contohnya):
Ini juga berfungsi untuk fungsi dan objek lain yang Anda buat. Ingatlah untuk menyertakan docstring
dengan fungsi Anda menggunakan string literal (""" """
dokumentasi).

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save('nama file', a)

Anda dapat menyimpannya sebagai "nama file.npy" dengan:
Anda dapat menggunakan np.load() untuk merekonstruksi array Anda.

In [ ]:
b = np.load('namafile.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'namafile.npy'

Jika Anda ingin memeriksa array Anda, Anda dapat menjalankan:

In [ ]:
print(b)

[[1 1]
 [2 2]]


Anda dapat menyimpan array NumPy sebagai file teks biasa seperti file .csv atau .txt dengan np.savetxt.
Misalnya, jika Anda membuat array ini:

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Anda dapat dengan mudah menyimpannya sebagai file .csv dengan nama “new_file.csv” seperti ini:

In [ ]:
np.savetxt('new_file.csv', csv_arr)

Anda dapat dengan cepat dan mudah memuat file teks yang disimpan menggunakan loadtxt():

In [ ]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

Fungsi savetxt() dan loadtxt() menerima parameter opsional tambahan seperti header, footer,
dan pembatas. Meskipun file teks lebih mudah untuk dibagikan, file .npy dan .npz lebih kecil dan
lebih cepat dibaca. Jika Anda memerlukan penanganan yang lebih canggih terhadap file teks
Anda (misalnya, jika Anda perlu bekerja dengan baris yang berisi nilai yang hilang), Anda dapat
menggunakan genfromtxt fungsi.

In [ ]:
a = np.array([[-2.58289208, 0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,0.94125714 , -0.14692469],
              [ 0,81299683, -0,95068423, 0,11769564],[ 0,20484034, 0,34784527, 1,96979195 ,
 0,51992837]])

Anda dapat membuat kerangka data Pandas

In [ ]:
a = np.array([2, 1, 5, 7, 4, 6, 8, 14, 10, 9, 18, 20, 22])

Jika Anda sudah menginstal Matplotlib, Anda dapat mengimpornya dengan:

In [ ]:
impor matplotlib.pyplot sebagai plt
plt.plot(a)

Yang perlu Anda lakukan untuk memplot nilai-nilai Anda adalah menjalankan:

In [ ]:
x = np.linspace(0, 5, 20)
y = np.linspace(0, 10, 20)
plt.plot(x, y, 'purple') #
baris
plt.plot(x, y, 'o') # titik

Dengan Matplotlib, Anda memiliki akses ke sejumlah besar opsi visualisasi.

In [ ]:
Y = np.rentang(-5, 5, 0,15)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
ax.plot_surface(X, Y,
Z, rstride=1, cstride=1, cmap='viridis')

Untuk membaca lebih lanjut tentang Matplotlib dan apa yang dapat dilakukannya, lihat dokumentasi resmi.
Untuk petunjuk mengenai instalasi Matplotlib,